[package]
name = "rust_share_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding = "0.2.33"
simple-error = "0.2.1"
memchr = "2.3.3"
log = "0.4"
base = { path = "../base" }